<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Core" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Messaging" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Persistence" />
    <PackageReference Include="SwiftBets.Contracts" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../SwiftBets.Notifications.Application/SwiftBets.Notifications.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Sql/*.sql" />
  </ItemGroup>
</Project>
