<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <ProjectReference Include="../SwiftBets.Notifications.Domain/SwiftBets.Notifications.Domain.csproj" />
  </ItemGroup>
</Project>
