<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Observability" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Web" />
    <ProjectReference Include="../SwiftBets.Notifications.Infrastructure/SwiftBets.Notifications.Infrastructure.csproj" />
  </ItemGroup>
</Project>
